spring:
  application:
    name: sale-config
  cloud:
    config:
      server:
        git:
          # 配置Git仓库位置
          uri: https://github.com/zkning/sale.git
          # 配置仓库路径下的相对位置，可以配置多个
          search-paths: /config-repo/**
          username:
          password:

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #eureka 服务端实例名称
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/

server:
  port: 8083
logging:
  level:
    root: info

# label 对应git不同分支
# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml