spring:
  application:
    name: sale-config
  cloud:
    config:
      server:
        git:
          # 配置Git仓库位置
          uri: https://github.com/zkning/sale.git
          # 配置仓库路径下的相对位置，可以配置多个
          search-paths: /config-repo/**
          username:
          password:
        overrides:  # 属性覆盖不会被客户端修改
          saleKey: saleValue
  rabbitmq:
    host: 10.10.30.11
    port: 5690
    username: test
    password: test2019
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #eureka 服务端实例名称
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/

server:
  port: 8083
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: ["refresh", "bus-refresh", "health"]

# label 对应git不同分支
# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml