server:
  port: 8087

# ribbon负载均衡策略
sale-product:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 商品服务url
productApi:
  getPrice: http://sale-product/product/getPrice
  getName: http://sale-product/product/getName