spring:
  application:
    name: sale-user

server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #eureka 服务端实例名称
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/

# ribbon负载均衡策略
sale-product:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 商品服务url
productApi:
  getPrice: http://sale-product/product/getPrice
  getName: http://sale-product/product/getName