spring:
  application:
    name: sale-eureke

server:
  port: 8084
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}
  client:
    register-with-eureka: false   # 是否把自己作为服务注册到其他服务注册中心(单节点无需启用)
    fetch-registry: false  # 是否从其他的服务中心同步服务列表(单节点无需启用)
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
  server:
    enable-self-preservation: true  # 自我保护机制
