logging:
  path: D:\www\wwwlogs
  level:
    root: info
spring:
  cloud:
    gateway:
      routes:
      - id: sale-user
        uri: lb://sale-user #lb://服务名(spring.application.name) Ribbon load balancer
        order: 0
        predicates:
        - Path=/user/**   # 拦截url
      - id: sale-product
#        uri: http://localhost:8088
        uri: lb://sale-product
        order: 1
        predicates:
        - Path=/product/**
        filters:
          - name: Authoriz # 自定义权限过滤器
            args:
              valve: true
          - AddRequestHeader=h1, HHHHHHHHHHHHHHHHH
          - AddRequestParameter=p1, AAAAAAAAAA
          - name: Hystrix
            args:
              name: authFallback # hystrix service id
              fallbackUri: forward:/fallback
  application:
    name: sale-gateway

hystrix.command.authFallback.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.command.authFallback.fallback.enabled: true

eureka:
  instance:
    prefer-ip-address: true #访问路径变为IP地址
    lease-expiration-duration-in-seconds: 5 #设置心跳的周期间隔(默认90s)[如果5s没响应默认服务宕机]
    lease-renewal-interval-in-seconds: 2  #设置心跳时间间隔(默认30s)
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    #在信息列表时显示主机名称
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
server:
  port: 8086
