spring:
  application:
    name: sophia-producer

server:
  port: 8088

eureka:
  instance:
#    hostname: sophia.producer.com   #eureka 服务端实例名称
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    instance-id: sophia.producer.com
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
